### PR TITLE
Cache CMS at deploy time

### LINKED ISSUE #29: Loading indicator / time to first paint
**Describe the bug**
Because we're fetching our entire CMS data on page load (and not just content), we don't have anything to display to the users for a few moments.

I can think of a few ways to approach this:
- Have a cached version of the CMS built _on deploy_ by the deploy script, that saves to something like `cached.json` - that is what is displayed to the user until we pull from the CMS (more work)
- Showing a loading indicator, using something like: https://klendi.github.io/react-top-loading-bar/ (less work)

I'd advocate for #2 just as it requires less work, and we can use the same visual indicator when navigating between pages

### PR DESCRIPTION
**Pull request by k8reindeer**
Whenever we deploy (i.e. merge to master) we go through each live city and grab it's current CMS values from airtable. This goes into cms-cache.json, and is loaded immediately so we don't have to wait for the network call to airtable after the page loads. 

This does mean, if you have an especially slow connection, and/or we've changed especially a lot in CMS-page-builder since the last deploy, you'll see a "flash" behavior where the old content appears for a second before being replaced by the latest content.

This is acceptable because the above-the-fold content really does not change that much. Also if it's ever an issue we can just do a no-op deploy to bust the cache.

### CODE REVIEW

File: pages/_app.jsx [hunk 1]
```diff
@@ -9,8 +9,12 @@ function NeighborExpress({ children }) {
   let { state, dispatch } = useContext(CMSContext);
 
   useEffect(() => {
+    import('../cms-cache.json').then((json) => json.records).then((records) => {
+      dispatch({ type: 'set-cached-records', payload: processRecords(records, state) })
+    });
+
```
Comment (keithk) [inline pages/_app.jsx:15]: Did you consider making this the initialState in the context directly vs setting it when the app renders?

Comment (k8reindeer) [reply pages/_app.jsx:15]: That sounds even faster! I'll look into it

Comment (k8reindeer) [reply pages/_app.jsx:15]: Hm, okay looking at this, I wasn't able to get it to be as fast as initialState, since the load from the file is also async -- it was populating the initial state with no records, and the local data wasn't coming any faster than the server data...

I also like having the separate action `set-cached-records` so we make sure we're never overwriting fresh content with stale/cached content.

Comment (keithk) [reply pages/_app.jsx:15]: Yup, after double checking that what I suggested made sense (it doesn't), I agree with your implementation here!

Reading:
https://gist.github.com/astoilkov/013c513e33fe95fa8846348038d8fe42
https://medium.com/@albertogasparin/the-pitfalls-of-async-operations-via-react-context-api-ab987d4290e6

**Review by keithk — APPROVED** [review]
